{% set version = "1.4.0" %}

package:
  name: partd
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/partd/partd-{{ version }}.tar.gz
  sha256: aa0ff35dbbcc807ae374db56332f4c1b39b46f67bf2975f5151e0b4186aed0d5

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - locket
    - toolz

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - partd

about:
  home: https://github.com/dask/partd
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Data structure for on-disk shuffle operations

extra:
  recipe-maintainers:
    - jcrist
    - mrocklin
    - TomAugspurger
    - jrbourbeau
