{% set version = "1.4.2" %}

package:
  name: partd
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/partd/partd-{{ version }}.tar.gz
  sha256: d022c33afbdc8405c226621b015e8067888173d85f7f5ecebb3cafed9a20f02c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - python >=3.9
    - locket
    - toolz

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - partd

about:
  home: https://github.com/dask/partd
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Data structure for on-disk shuffle operations

extra:
  recipe-maintainers:
    - jcrist
    - mrocklin
    - TomAugspurger
    - jrbourbeau
