{% set version = "0.3.7" %}

package:
  name: partd
  version: {{ version }}

source:
  fn: partd-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/partd/partd-{{ version }}.tar.gz
  sha256: fdc344bca07f3b10645cc380950a00bbfcdbf993f3396715eb0936d14811cd18

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - locket
    - toolz

  run:
    - python
    - locket
    - toolz

test:
  imports:
    - partd

about:
  home: https://github.com/dask/partd
  license: BSD 3-Clause
  summary: Data structure for on-disk shuffle operations

extra:
  recipe-maintainers:
    - jcrist
    - mrocklin
    - koverholt
